services:
  web:
    container_name: ${DOCKER_NAME_PREFIX:-osmdev}-web
    image: ${DOCKER_NAME_PREFIX:-osmdev}-web
    build:
      context: ${BASE_REPO:-./../openstreetmap-website}
    environment:
      PIDFILE: /tmp/pids/server.pid
      DOMAIN_NAME: ${DOMAIN_NAME:-localhost}
      INSTANCE_SLUG: ${DOCKER_NAME_PREFIX:-osmdev}
    volumes:
      - ${BASE_REPO:-./../openstreetmap-website}:/app
      - ./start.sh:/docker/start.sh
      - ./scripts:/docker/scripts
      - ./config/settings.local.yml:/app/config/settings.local.yml
      - ./config/database.yml:/app/config/database.yml
      - ./config/storage.yml:/app/config/storage.yml
      - /app/node_modules/
      - web-tmp:/app/tmp
      - web-storage:/app/storage
    networks:
      - local_network
      - osm-proxy
    tmpfs:
      /tmp/pids/
    stdin_open: true
    tty: true
    command: /docker/start.sh
    depends_on:
      - db
      - memcached
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.docker.network=osm-proxy
      - traefik.http.routers.${DOCKER_NAME_PREFIX:-osmdev}.rule=Host(`${DOMAIN_NAME:-localhost}`)
      - traefik.http.routers.${DOCKER_NAME_PREFIX:-osmdev}.entrypoints=websecure
      - traefik.http.routers.${DOCKER_NAME_PREFIX:-osmdev}.tls.certresolver=le
      - traefik.http.services.${DOCKER_NAME_PREFIX:-osmdev}.loadbalancer.server.port=3000

  memcached:
    container_name: ${DOCKER_NAME_PREFIX:-osmdev}-memcached
    image: memcached:latest
    networks:
      - local_network

  db:
    container_name: ${DOCKER_NAME_PREFIX:-osmdev}-db
    image: ${DOCKER_NAME_PREFIX:-osmdev}-db 
    build:
      context: ${BASE_REPO:-./../openstreetmap-website}
      dockerfile: docker/postgres/Dockerfile
    ports:
      - "54321:5432"
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - local_network

volumes:
  web-tmp:
  web-storage:
  db-data:

networks:
  local_network:
  osm-proxy:
    external: true
