services:
  web:
    container_name: web
    build:
      context: ./../openstreetmap-website
    ports:
      - "3000:3000"
    environment:
      PIDFILE: /tmp/pids/server.pid
    volumes:
      - ./../openstreetmap-website:/app
      - ./start.sh:/docker/start.sh
      - ./config/settings.local.yml:/app/config/settings.local.yml
      - ./config/database.yml:/app/config/database.yml
      - ./config/storage.yml:/app/config/storage.yml
      - /app/node_modules/
      - web-tmp:/app/tmp
      - web-storage:/app/storage
    networks:
      - local_network
    tmpfs:
      /tmp/pids/
    stdin_open: true
    tty: true
    command: /docker/start.sh
    depends_on:
      - db
      - memcached
    env_file:
      - .env

  memcached:
    container_name: memcached
    image: memcached:latest
    ports:
      - '11211:11211'
    networks:
      - local_network

  db:
    container_name: db
    build:
      context: ./../openstreetmap-website
      dockerfile: docker/postgres/Dockerfile
    ports:
      - "54321:5432"
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - local_network

volumes:
  web-tmp:
  web-storage:
  db-data:
    driver: local
    name: pg_data

networks:
  local_network:
    driver: bridge
