development:
  primary:
    adapter: postgresql
    host: db
    database: openstreetmap
    username: postgres
    password: openstreetmap
    encoding: utf8
<% if ENV["GPS_ENABLED"] == "1" %>
  gps:
    adapter: postgresql
    host: gps-db
    database: openstreetmap_gps
    username: postgres
    password: openstreetmap
    encoding: utf8
    connect_timeout: 3
    migrations_paths: db/gps_migrate
<% end %>
