development:
  primary:
    adapter: postgresql
    host: db
    database: openstreetmap
    username: postgres
    password: openstreetmap
    encoding: utf8
  gps:
    adapter: postgresql
    host: db
    database: openstreetmap_gps
    username: postgres
    password: openstreetmap
    encoding: utf8
    connect_timeout: 3
    migrations_paths: db/gps_migrate

test:
  primary:
    adapter: postgresql
    host: db
    database: osm_test
    username: postgres
    password: openstreetmap
    encoding: utf8
  gps:
    adapter: postgresql
    host: db
    database: osm_test_gps
    username: postgres
    password: openstreetmap
    encoding: utf8
    connect_timeout: 3
    migrations_paths: db/gps_migrate
